name: '✨ 기능 추가'
description: 기능 추가 시 해당 이슈 템플릿을 사용하여 이슈를 생성해주세요.
title: '[Feat]'
body:
  - type: textarea
    attributes:
      label: ✨ 이슈 설명
      placeholder: 이슈에 대해 간략하게 설명해주세요
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📝 작업 내용
      placeholder: 진행할 작업에 대해 적어주세요
    validations:
      required: true
